[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "customer-demos"
version = "0.0.0"
description = "Demo project for CI runner testing"
readme = "README.md"
authors = [ { name = "Oleksandr Gugnin" } ]
license = { text = "MIT" }
